# Generated by Django 6.0.4 on 2026-05-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='year_born',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='released_year',
            field=models.IntegerField(),
        ),
    ]
