# Generated by Django 6.0.4 on 2026-05-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
