# Generated by Django 6.0.4 on 2026-05-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('released_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pages', models.IntegerField()),
            ],
        ),
    ]
