# Generated by Django 6.0.6 on 2026-06-29 10:30

import pages.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_blogpost_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/', validators=[pages.validators.validate_image_size], verbose_name='Cover Image'),
        ),
    ]
