# Generated by Django 6.0.6 on 2026-06-29 23:56

import pages.models
import pages.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_blogpost_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=pages.models.blog_image_upload_path, validators=[pages.validators.validate_image_size], verbose_name='Cover Image'),
        ),
    ]
