# Generated by Django 6.0.5 on 2026-05-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gerne',
            field=models.CharField(default='RGP', max_length=50),
        ),
    ]
