# Generated by Django 6.0.5 on 2026-05-13 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_game_gerne'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gerne',
            new_name='genre',
        ),
    ]
