# Generated by Django 6.0.4 on 2026-04-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
