# Generated by Django 6.0.4 on 2026-04-20 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_student_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='views',
        ),
    ]
