# Generated by Django 6.0.4 on 2026-04-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_student_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='points_save',
            field=models.IntegerField(null=True),
        ),
    ]
