# Generated by Django 6.0.4 on 2026-04-20 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_student_points_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='points',
        ),
    ]
