# Generated by Django 6.0.4 on 2026-04-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_student_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='No Added'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='No Added'),
        ),
    ]
