# Generated by Django 6.0.4 on 2026-04-20 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_student_first_name_student_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
