# Generated by Django 6.0.4 on 2026-04-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
